# Generated by Django 3.0.2 on 2020-01-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resistome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assembly', to='resistome.Sample'),
        ),
        migrations.AlterField(
            model_name='datafiles',
            name='annotation_gff',
            field=models.FileField(upload_to='annotationDATA'),
        ),
        migrations.AlterField(
            model_name='datafiles',
            name='annotation_protein_fasta',
            field=models.FileField(upload_to='annotationDATA'),
        ),
        migrations.AlterField(
            model_name='datafiles',
            name='annotation_transcript_fasta',
            field=models.FileField(upload_to='annotationDATA'),
        ),
        migrations.AlterField(
            model_name='datafiles',
            name='assembly',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resistome.Assembly'),
        ),
        migrations.AlterField(
            model_name='datafiles',
            name='assembly_fasta',
            field=models.FileField(upload_to='assemblyFASTA'),
        ),
        migrations.AlterField(
            model_name='mlst',
            name='assembly',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mlst', to='resistome.Assembly'),
        ),
    ]
