# Generated by Django 3.0.2 on 2020-01-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resistome', '0002_auto_20200129_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaffold',
            name='centrifuge_seq',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='scaffold',
            name='centrifuge_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resistome.Species', verbose_name='Centrifuge classification'),
        ),
    ]
