# Generated by Django 3.0.2 on 2020-01-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resistome', '0003_auto_20200130_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scaffold',
            name='centrifuge_seq',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
