# Generated by Django 3.0.2 on 2020-01-31 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resistome', '0004_auto_20200130_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='scaffold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_set', related_query_name='gene_set', to='resistome.Scaffold'),
        ),
        migrations.AlterField(
            model_name='rgi',
            name='annotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rgi_set', related_query_name='rgi_set', to='resistome.Annotation'),
        ),
    ]
