# Generated by Django 3.0.2 on 2020-02-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resistome', '0005_auto_20200131_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaffold',
            name='jbrowse_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
