# Generated by Django 3.0.2 on 2020-02-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resistome', '0008_auto_20200204_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scaffold',
            name='centrifuge_species',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Centrifuge classification'),
        ),
    ]
