# Generated by Django 3.0.2 on 2020-02-06 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resistome', '0009_auto_20200206_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='other_resistance_mechanisms',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sequence_type',
        ),
    ]
